---
- name: Listen for storage-monitor events
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ dt_host }}"
        dt_api_token: "{{ dt_token }}"
        delay: 5

  rules:
    # - name: DYNATRACE - Document and remediate storage-monitor Problem
    #   condition: event.payload.State == "OPEN"
    #   action:
    #     run_job_template:
    #       name: StorageRemediation
    #       organization: Default
    #       job_args:
    #         extra_vars:
    #           message: "'Hi, World!' -Event-Driven Ansible"

    # - name: DYNATRACE - Problem resolved
    #   condition: event.payload.State == "RESOLVED"
    #   action:
    #     debug:
    #       msg: "{{ event.payload.ProblemID }} marked as RESOLVED"
        
    - name: DYNATRACE - Unhandled condition
      condition: event.payload is defined
      action:
        debug:
          msg: "Unhandled event condition from Dynatrace"
