---
- name: Listen for storage-monitor events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Rule - Print event information
      condition: event.payload.State == "OPEN"
      action:
        run_job_template:
          name: StorageRemediation
          organization: Default
          job_args:
            extra_vars:
              message: Hi, World!
              sleep: 1
