---
- name: Listen for storage-monitor events
  hosts: all
  sources:
    - ansible.eda.azure_service_bus:
        conn_str: "{{ conn_str }}"
        queue_name: "{{ queue_name }}"

  rules:
    - name: Document and remediate storage-monitor Problem
      condition: event.body.application == "dynatrace" and event.body.State == "OPEN"
      action:
        run_job_template:
          name: StorageRemediation
          organization: Default
          job_args:
            extra_vars:
              message: "'Hi, World!' -Event-Driven Ansible"

    - name: DEBUG Dynatrace rulebook
      condition: event.body.application == "dynatrace"
      action:
        debug:
