---
- name: Listen for storage-monitor events
  hosts: all
  sources:
    - ansible.eda.azure_service_bus:
        conn_str: "{{ conn_str }}"
        queue_name: "{{ queue_name }}"

  rules:
    - name: Rule - Print event information
      condition: event.body.State == "OPEN"
      action:
          debug:
#         run_job_template:
#           name: StorageRemediation
#           organization: Default
#           job_args:
#             extra_vars:
#               message: Hi, World!
#               sleep: 1
