---
- name: storage-monitor problems 
  hosts: all
  gather_facts: false
  collections:
    - servicenow.itsm
  vars:
    username: "{{ lookup('env', 'SN_USERNAME') }}"
    password: "{{ lookup('env', 'SN_PASSWORD') }}"
    instance: "{{ lookup('env', 'SN_HOST') }}"
    short_description: 
    description:

  tasks:

    - name: Create incident
      servicenow.itsm.incident:
        state: new
        caller: "{{ username }}"
        short_description: "{{ ansible_eda.event.payload.source }}"
        description: |
            "{{ description }}"
        impact: low
        urgency: low
      register: new_incident
      delegate_to: localhost
      ignore_errors: true

    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true
      delegate_to: localhost
      ignore_errors: true

    - debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"
      ignore_errors: true
        
    - name: Extend volume
      ansible.builtin.service:
        name: httpd
        state: started
      delegate_to: node1
